todo-application/Models/Data/SeedData.cs
using Microsoft.EntityFrameworkCore;

namespace todo_application.Models.Data
{
    public static class SeedData
    {
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            TodoDbContext context = app.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<TodoDbContext>();

            context.Database.EnsureCreated();

            if (context.Database.GetPendingMigrations().Any())
            {
                context.Database.Migrate();
            }
            if (!context.TodoLists.Any())
            {
                context.TodoLists.AddRange(
                    new TodoList
                    {
                        Name = "Grocery List",
                        Items = new List<TodoItem>
                        {
                        new TodoItem { Title = "Buy milk", Description = "1 gallon of whole milk", DueDate = new DateTime(2024, 12, 31), Status = TodoItemStatus.NotStarted },
                        new TodoItem { Title = "Buy bread", Description = "1 loaf of whole wheat bread", DueDate = new DateTime(2024, 12, 31), Status = TodoItemStatus.NotStarted },
                        new TodoItem { Title = "Buy eggs", Description = "1 dozen large eggs", DueDate = new DateTime(2024, 12, 31), Status = TodoItemStatus.NotStarted }
                        }
                    },
                    new TodoList
                    {
                        Name = "House Cleaning List",
                        Items = new List<TodoItem>
                        {
                        new TodoItem { Title = "Vacuum living room", Description = "Vacuum the carpet in the living room", DueDate = new DateTime(2024, 12, 31), Status = TodoItemStatus.NotStarted },
                        new TodoItem { Title = "Dust furniture", Description = "Dust all the furniture in the house", DueDate = new DateTime(2024, 12, 31), Status = TodoItemStatus.NotStarted },
                        new TodoItem { Title = "Mop kitchen floor", Description = "Mop the kitchen floor with a wet mop", DueDate = new DateTime(2024, 12, 31), Status = TodoItemStatus.NotStarted }
                        }
                    }
                );
                context.SaveChanges();
            }
        }
    }
}

todo-application/Models/ErrorViewModel.cs
namespace todo_application.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

todo-application/Models/TodoDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace todo_application.Models
{
    public class TodoDbContext : DbContext
    {
        public TodoDbContext(DbContextOptions<TodoDbContext> options) : base(options) { }
        public DbSet<TodoList> TodoLists { get; set; }
        public DbSet<TodoItem> TodoItems { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TodoList>()
                .HasMany(e => e.Items)
                .WithOne(e => e.TodoList)
                .IsRequired(false);

            modelBuilder.Entity<TodoList>()
                .HasIndex(x => x.Name)
                .IsUnique();

            modelBuilder.Entity<TodoItem>()
                .HasOne(e => e.TodoList)
                .WithMany(e => e.Items);
        }


    }
}

todo-application/Models/TodoItem.cs
using System.ComponentModel.DataAnnotations;

namespace todo_application.Models
{
    public class TodoItem
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime DueDate { get; set; }
        public DateTime CreationDate { get; private set; }

        public TodoItemStatus Status { get; set; }

        public TodoList TodoList { get; set; }

        public TodoItem()
        {
            CreationDate = DateTime.Now;
            Status = TodoItemStatus.NotStarted;
        }
    }
    public enum TodoItemStatus
    {
        NotStarted,
        InProgress,
        Completed
    }
}

todo-application/Models/TodoList.cs
namespace todo_application.Models
{
    public class TodoList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<TodoItem>? Items { get; set; }
    }
}

todo-application/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Net;
using todo_application.Models;

namespace todo_application.Controllers
{
    public class ToDoController : Controller
    {
        private readonly ILogger<ToDoController> _logger;
        private readonly TodoDbContext _db;

        public ToDoController(ILogger<ToDoController> logger, TodoDbContext todoDbContext)
        {
            _logger = logger;
            _db = todoDbContext;
        }

        public IActionResult Index()
        {
            var lists = _db.TodoLists.Include(x => x.Items).ToList();
			return View(lists);
        }

        [Route("/list/{listId}")]
        public IActionResult List(int listId)
        {
            var list = _db.TodoLists.Include(x => x.Items).FirstOrDefault(x => x.Id == listId);
			if (list is null)
			{
				return NotFound();
			}
			return View(list);
        }

        [HttpGet]
        [Route("/create")]
        public IActionResult Create()
        {
            return View();
        }

        [Route("/create")]
        [HttpPost]
        public IActionResult Create(TodoList todoList)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            _db.TodoLists.Add(todoList);
            _db.SaveChanges();
            var id = todoList.Id;
            return Redirect($"create/{id}");
        }

		[HttpGet]
		[Route("/create/{listId}")]
		public IActionResult CreateItems(int listId)
        {
			var list = _db.TodoLists.Include(x => x.Items).FirstOrDefault(x => x.Id == listId);
			if (list is null)
			{
				return NotFound();
			}
			ViewBag.ToDoList = list;
			return View();
        }

        [Route("/create/{listId}")]
        [HttpPost]
        public IActionResult CreateItems(int listId,TodoItem todoItem)
        {
            var list = _db.TodoLists.Include(x => x.Items).FirstOrDefault(x => x.Id == listId);
            if(list is null)
            {
                return NotFound();
            }
            ViewBag.ToDoList = list;
            todoItem.TodoList = list;
			_db.TodoItems.Add(todoItem);
            _db.SaveChanges();
			ModelState.Clear();
			return View();
        }

        [HttpGet]
        [Route("/edit/{id}")]
		public IActionResult Edit(int id)
		{
            var list = _db.TodoLists.FirstOrDefault(x => x.Id == id);
			if (list is null)
			{
				return NotFound();
			}
            return View(list);
		}

        [HttpPost]
		[Route("/edit/{id}")]
		public IActionResult Edit(int id, TodoList todoList)
		{
            var list = _db.TodoLists.FirstOrDefault(x => x.Id == id);
			if (list is null)
			{
				return NotFound();
			}
            list.Name = todoList.Name;
            _db.SaveChanges();
            return RedirectToAction("Index");
		}

		[HttpGet]
		[Route("/item/{id}")]
		public IActionResult EditItem(int id)
		{
			var item = _db.TodoItems.Include(x => x.TodoList).FirstOrDefault(x => x.Id == id);
			if (item is null)
			{
				return NotFound();
			}
			return View(item);
		}

		[HttpPost]
		[Route("/item/{id}")]
		public IActionResult EditItem(int id, TodoItem todoItem)
		{
			var item = _db.TodoItems.Include(x => x.TodoList).FirstOrDefault(x => x.Id == id);
			if (item is null)
			{
				return NotFound();
			}
            item.Title = todoItem.Title;
            item.Description = todoItem.Description;
            item.DueDate = todoItem.DueDate;
            item.Status = todoItem.Status;
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

        [HttpGet]
        public IActionResult ChangeStatus(int id)
        {
			var item = _db.TodoItems.Include(x => x.TodoList).FirstOrDefault(x => x.Id == id);
            return View(item);
        }

        [HttpPost]
        public IActionResult ChangeStatus(int id, TodoItem todoItem)
        {
			var item = _db.TodoItems.Include(x => x.TodoList).FirstOrDefault(x => x.Id == id);
			if (item is null)
			{
				return NotFound();
			}
            item.Status = todoItem.Status;
            _db.SaveChanges();  
            return Redirect($"/list/{item.TodoList.Id}");
        }

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

todo-application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todo_application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/todo_application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ToDo" asp-action="Index">todo_application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Create">Create List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

todo-application/Views/ToDo/ChangeStatus.cshtml
@model todo_application.Models.TodoItem;
@using static todo_application.Models.TodoItemStatus;

<div>
	<h1 class="form-title">Change Status</h1>
	<form class="form" asp-action="changestatus" asp-controller="ToDo">
		<label class="form-label" asp-for="Status">@TodoItemStatus.Completed</label>
		<input type="radio" asp-for=Status value="@TodoItemStatus.Completed"/>
		<br />
		<label class="form-label" asp-for="Status">@TodoItemStatus.InProgress</label>
		<input type="radio" asp-for="Status" value="@TodoItemStatus.InProgress"/>
		<br />
		<label class="form-label" asp-for="Status">@TodoItemStatus.NotStarted</label>
		<input type="radio" asp-for="Status" value="@TodoItemStatus.NotStarted" />
		<br />
		<button class="button" type="submit">Change</button>
		<br />
		<button class="button" type="button" onclick="location.href='@Url.Action("Index", "ToDo")'">Back</button>
	</form>
</div>

todo-application/Views/ToDo/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model todo_application.Models.TodoList;
@{

}
<div>
	<h1 class="form-title">Add List</h1>
	<form class="form" asp-action="create" asp-controller="ToDo">
		<label class="form-label" asp-for="Name">Name</label>
		<input class="form-input" asp-for="Name" />
		<button class="button" type="submit">Create</button>
		<br />
		<button class="button" type="button" onclick="location.href='@Url.Action("Index", "ToDo")'">Back</button>
	</form>
</div>

todo-application/Views/ToDo/CreateItems.cshtml
@model todo_application.Models.TodoItem;

<div>
	<h1 class="form-title">@ViewBag.ToDoList.Name</h1>
	<form class="form" asp-action="CreateItems" asp-controller="ToDo">
		<div>
			<label class="form-label" asp-for="Title">Title</label>
			<input class="form-input" asp-for="Title" />
		</div>
		<br />
		<div>
			<label class="form-label" asp-for="Description">Description</label>
			<input class="form-input" asp-for="Description" />
		</div>
		<br />
		<div>
			<label class="form-label" asp-for="DueDate">DueDate</label>
			<input class="form-input" type="date" asp-for="DueDate" />
		</div>
		<br />
		<button class="button" type="submit">Add Item</button>
		<br />
		<button class="button" type="button" onclick="location.href='@Url.Action("Index", "ToDo")'">Back</button>
	</form>
	<br />
	<div>
		<ul>List Items: </ul>
		@if (ViewBag.ToDoList.Items.Count == 0)
		{
			<p>no list items yet</p>
		}
		else
		{
			@foreach (var items in ViewBag.ToDoList.Items)
			{
				<li>@items.Title</li>
			}
		}
	</div>
</div>

todo-application/Views/ToDo/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model todo_application.Models.TodoList;
@{

}
<div>
	<h1 class="form-title">Edit Name</h1>
	<form class="form" asp-action="edit" asp-controller="ToDo">
		<label class="form-label" asp-for="Name">Name</label>
		<input class="form-input" asp-for="Name" placeholder="@Model.Name" />
		<button class="button" type="submit">Edit</button>
		<br />
		<button class="button" type="button" onclick="location.href='@Url.Action("Index", "ToDo")'">Back</button>
	</form>
</div>

todo-application/Views/ToDo/EditItem.cshtml
@model todo_application.Models.TodoItem;
@using static todo_application.Models.TodoItemStatus;

<div>
	<h1 class="form-title">Edit item</h1>
	<form class="form" asp-action="edititem" asp-controller="ToDo">
		<input type="hidden" asp-for="TodoList" />
		<div>
			<label class="form-label" asp-for="Title">Title</label>
			<input class="form-input" asp-for="Title" placeholder="@Model.Title" />
		</div>
		<br />
		<div>
			<label class="form-label" asp-for="Description">Description</label>
			<input class="form-input" asp-for="Description" placeholder="@Model.Description" />
		</div>
		<br />
		<div>
			<label class="form-label" asp-for="DueDate">DueDate</label>
			<input class="form-input" type="date" asp-for="DueDate" placeholder="@Model.DueDate" />
		</div>
		<div>
			<label class="form-label" asp-for="Status">Status</label>
			<select class="form-select" name="Status">
				<option value="@TodoItemStatus.NotStarted">@TodoItemStatus.NotStarted</option>
				<option value="@TodoItemStatus.InProgress">@TodoItemStatus.InProgress</option>
				<option value="@TodoItemStatus.Completed">@TodoItemStatus.Completed</option>
			</select>
		</div>
		<button class="button" type="submit">Edit</button>
		<br />
		<button class="button" type="button" onclick="location.href='@Url.Action("Index", "ToDo")'">Back</button>
	</form>
	<br />
	<div>
	</div>

todo-application/Views/ToDo/Index.cshtml
@model IEnumerable<todo_application.Models.TodoList>

@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="container-title index-title">Hello</h1>
	<p class="container-description index-description">Today you have @Model.ToList().Count tasks</p>
	@foreach (var list in Model)
	{
		<div class="container-index">
			<h2 class="container-index-title">
				<a  asp-action="list" asp-route-listId="@list.Id">@list.Name</a>
				<span class="icon"><a asp-action="edit" asp-route-id="@list.Id">&#9998;</a></span>
			</h2>
			<p>@list.Items?.Count tasks</p>
		</div>
	}
	<p><a class="link index-link" asp-action="create" asp-controller="Todo" >Create list</a></p>
</div>

todo-application/Views/ToDo/List.cshtml
@model todo_application.Models.TodoList

@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="container-title">@Model.Name</h1>
	<div class="container-list">
		@foreach (var item in Model.Items)
		{
			<div class="container-list-inner">
				<h2 class="container-list-title">@item.Title</h2>
				<p>@item.Description</p>
				<p>Created on @item.CreationDate</p>
				<p>Due by @item.DueDate</p>
				@if (@item.Status == TodoItemStatus.NotStarted)
				{
					<p class="status-red">
						Not started
						<span class="icon"><a asp-action="changestatus" asp-route-id="@item.Id">&#9998;</a></span>
					</p>
				}
				else if (item.Status == TodoItemStatus.InProgress)
				{
					<p class="status-blue">
						In progress
						<span class="icon"><a asp-action="changestatus" asp-route-id="@item.Id">&#9998;</a></span>
					</p>
				}
				else
				{
					<p class="status-green">
						Completed &#10003;
						<span class="icon"><a asp-action="changestatus" asp-route-id="@item.Id">&#9998;</a></span>
					</p>
				}
				<p class="list-link-p"><a class="list-link link" asp-action="edititem" asp-route-id="@item.Id">Edit list</a></p>
			</div>
		}
	</div>
	<div class="list-buttons">
		<button class="list-button button" type="button" onclick="location.href='@Url.Action("CreateItems", "ToDo", new {listId = Model.Id})'">Add items</button>
		<button class="list-button button" type="button" onclick="location.href='@Url.Action("Index", "ToDo")'">Back</button>
	</div>
</div>